let songs = [
    {
        name: 'I Did Something Bad',
        path: 'songs/I Did Something Bad.mp3',
        artist: 'Taylor Swift',
        cover: 'img/song/reput.jpg',
    },
    {
        name: 'Alon',
        path: 'songs/Alone.mp3',
        artist: 'Alan Wakar',
        cover: 'img/ar/alan.jpg',
    },
    {
        name: 'Bilionera',
        path: 'songs/Bilionera.mp3',
        artist: 'Otilia Bruma',
        cover: 'img/ar/oti.jpeg',
    },
    {
        name: 'Danza Kuduro',
        path: 'songs/Danza Kuduro.mp3',
        artist: 'FF5',
        cover: 'img/song/DK.jpeg',
    },
    {
        name: 'Darkside',
        path: 'songs/Darkside.mp3',
        artist: 'Alan Wakar',
        cover: 'img/ar/alan.jpg',
    },  
    {
        name: 'Galway Girl',
        path: 'songs/Galway Girl.mp3',
        artist: 'Ed Sheeran',
        cover: 'img/ar/ed.jpeg',
    },  
    {
        name: 'Maps',
        path: 'songs/Maps.mp3',
        artist: 'Maroon 5',
        cover: 'img/ar/5.jpg',
    },  
    {
        name: 'Never Be the Same',
        path: 'songs/Never Be the Same.mp3',
        artist: 'Camila',
        cover: 'img/ar/camila.jpeg',
    },  
    {
        name: 'New Rules',
        path: 'songs/New Rules.mp3',
        artist: 'Dua Lipa',
        cover: 'img/ar/dua.jpeg',
    },  
    {
        name: 'No Lie',
        path: 'songs/No Lie.mp3',
        artist: 'Dua Lipa',
        cover: 'img/ar/dua.jpeg',
    },
    {
        name: 'Pepas',
        path: 'songs/Pepas.mp3',
        artist: 'pepas',
        cover: 'img/song/pepas.jpeg',
    },
    {
        name: 'Perfect',
        path: 'songs/Perfect.mp3',
        artist: 'Ed Sheeran',
        cover: 'img/ar/ed.jpeg',
    },
    {
        name: 'Real Friends',
        path: 'songs/Real Friends.mp3',
        artist: 'Camila',
        cover: 'img/ar/camila.jpeg',
    },
    {
        name: 'Shape Of You',
        path: 'songs/Shape Of You.mp3',
        artist: 'Ed Sheeran',
        cover: 'img/ar/ed.jpeg',
    },
    {
        name: 'You Belong With Me',
        path: 'songs/You Belong With Me.mp3',
        artist: 'Taylor Swift',
        cover: 'img/ar/TT.jpeg',
    },
]